<?php
	$row = $lead["id"];
	
	$action_item_due_date = $lead['action_item_due_date'];
	date_default_timezone_set('America/Denver');
	$today_date = date("Y-m-d H:i:s");
	
	$phone_number = $lead["phone_number"];
	if(empty($phone_number))
	{
		$formatted_phone_number = "";
	}
	else
	{
		$formatted_phone_number = "(".substr($phone_number,0,3).") ".substr($phone_number,3,3)."-".substr($phone_number,6,4);
	}
	
	if($action_item_due_date=== NULL)
	{
		$action_item_due_date = '';
	}
	else
	{
		$action_item_due_date = date('m/d/y', strtotime($action_item_due_date));
	}
	
	//echo "ID ".$lead['assigned_recruiter_id'];
	if(is_null($lead['assigned_recruiter_id']))
	{
		$recruiter_name = '';
	}
	else
	{
		$recruiter_id = $lead['assigned_recruiter_id'];
		$where = null;
		$where['id'] = $recruiter_id;
		$recruiter = db_select_user($where);
		$recruiter_name = $recruiter['first_name']." ".$recruiter['last_name'];
	}
	
?>

<table data-id="<?=$lead["id"]?>" style="table-layout:fixed;"width="990">
	<tr style="line-height:25px;">
		<td onclick="open_lead_details(<?= $row ?>)" style="width:39px;" class="ellipsis"
		<?php if(!is_null($lead['application_datetime'])):?>
		title="<?php echo date('m/d/y g:i:sa', strtotime($lead['application_datetime']))." Lead Generated By ".$lead['user_submitted']; ?>"
		<?php endif ?>
		>
			<?php if(!is_null($lead['application_datetime'])):?>
			<?php echo date('m/d/y', strtotime($lead['application_datetime'])); ?>
			<?php endif ?>
		</td>
		<td onclick="open_lead_details(<?= $row ?>)" style="width:46px;"
			<?php if(!is_null($lead['availability_date'])):?>
			title="<?php echo date('m/d/y', strtotime($lead['availability_date']));?>" 
			<?php endif ?>
		>
			<?php if(!is_null($lead['availability_date'])):?>
				<?php echo date('m/d/y', strtotime($lead['availability_date']));?>
			<?php endif ?>
		</td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $lead['why_called_in']?>" class="ellipsis" style="width:47px;"><?php echo $lead['why_called_in']?></td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $lead['first_name']." ".$lead['last_name']?>" style="width:80px;" class="ellipsis" style="width:120px;"><?php echo $lead['first_name']." ".$lead['last_name']?></td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $formatted_phone_number ?>" class="ellipsis" style="width:77px;"><?php echo $formatted_phone_number ?></td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $recruiter_name?>" class="ellipsis" style="width:74px;"><?php echo $recruiter_name ?></td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $lead['submitted_to']?>" class="ellipsis" style="width:72px;"><?php echo $lead['submitted_to'] ?></td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $lead['current_state']?>" class="ellipsis" style="width:26px;"><?php echo $lead['current_state']?></td>
		<td onclick="open_lead_details(<?= $row ?>)" class="ellipsis" title="<?php echo $action_item_due_date?>" style="width:45px;
		<?php if(date('Y-m-d H:i:s', strtotime($action_item_due_date))<=$today_date):?>
			color:red;
		<?php endif ?>
		">
			<?php echo $action_item_due_date?>
		</td>
		<td onclick="open_lead_details(<?= $row ?>)" title="<?php echo $lead['lead_status']?>" class="ellipsis" style="width:96px;"><?php echo $lead['lead_status']?></td>
		<div style="min-height:30px;display:table-cell;vertical-align:middle;">
			<td style="width:22px;text-align:right;">
				<?php if(!empty($lead['applicant_status_log'])):?>
					<img onclick="open_notes(<?=$row?>)" src="<?= base_url("images/nextgen_notes_filled_360.png")?>" style="height:20px;position:relative;top:5px;right:5px;"
					title="<?php echo $lead['applicant_status_log']?>"
					/>
				<?php else:?>
					<img onclick="open_notes(<?=$row?>)" src="<?= base_url("images/nextgen_notes_empty_360.png")?>" style="height:20px;position:relative;top:5px;right:5px;"/>
				<?php endif?>
			</td>
		</div>
	</tr>
</table>